services:
  orders-db:
    image: postgres:15
    container_name: orders_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: orders_db
    networks:
      - gozon-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d orders_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  payments-db:
    image: postgres:15
    container_name: payments_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: payments_db
    volumes:
      - ./payments-service/db:/docker-entrypoint-initdb.d
    networks:
      - gozon-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d payments_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - gozon-net
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 10s
      retries: 5

  orders-service:
    build: ./orders-service
    container_name: orders_service
    depends_on:
      orders-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - gozon-net

  payments-service:
    build: ./payments-service
    container_name: payments_service
    depends_on:
      payments-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - gozon-net

  api-gateway:
    image: nginx:alpine
    container_name: api_gateway
    ports:
      - "8000:80"
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend:/usr/share/nginx/html:ro
    depends_on:
      - orders-service
      - payments-service
    networks:
      - gozon-net

networks:
  gozon-net:
    driver: bridge